'use client'
import React, { useState, FormEvent, useEffect, useRef } from 'react'
import { Layout, TextEntryQuestion } from '@/types'

interface QuestionAnswerProps<T> {
  layout: Layout<T>
  onSubmit: (answer: string) => void
}

export default function TextEntryComponent({
  layout,
  onSubmit,
}: QuestionAnswerProps<TextEntryQuestion>) {
  const [answer, setAnswer] = useState('')
  const [isAnswerVisible, showAnswer] = useState(false)
  const answerInputRef = useRef(null)

  const question: TextEntryQuestion = layout.question

  useEffect(() => {
    // Hide answer when we move to next question
    showAnswer(false)

    // Reset form
    setAnswer('')

    // Focus on answer
    if (answerInputRef.current) {
      ;(answerInputRef.current as HTMLInputElement).focus()
    }
  }, [question.key])

  // Generated by Copilot

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault()

    if (!answer.trim()) return

    // Submit the answer
    onSubmit(answer.trim())

    // Show answer
    showAnswer(true)
  }

  return (
    <section className="group-block" aria-labelledby="text-entry">
      <h3 id="text-entry">{question.contentType || question.type}</h3>
      <div className="question-text">{question.text}</div>
      <form onSubmit={handleSubmit}>
        <div className="form-row">
          <label htmlFor="answer">{question.hint}</label>
          <input
            id="answer"
            type="text"
            value={answer}
            onChange={e => setAnswer(e.target.value)}
            required
            ref={answerInputRef}
          />
        </div>
        <div className="form-row">
          <button id="submit-answer" type="submit" disabled={!answer.trim()}>
            Submit Answer
          </button>
        </div>
        <div className="form-row">
          <div>{`Question ${layout.index + 1} of ${layout.collection.itemCount}`}</div>
          <div className={isAnswerVisible ? '' : 'hidden'}>{question.key}</div>
        </div>
      </form>
    </section>
  )
}
