import React, { Dispatch, SetStateAction } from 'react'

import { CollectionItemTermPicker } from './CollectionItemTermPicker'
import { CollectionItemTraitPicker } from './CollectionItemTraitPicker'
import { CollectionItemTopicPicker } from './CollectionItemTopicPicker'

import { CollectionInatTaxonPicker } from '@/components/common/taxon/CollectionInatTaxonPicker'

import { ContentHandlerType, Operation, Taxon, Collection } from '@/types'

// Generated by Copilot
type ComponentProps = {
  setItems: Dispatch<SetStateAction<unknown[] | undefined>>
  items: string | Taxon[]
  operation?: Operation
  collection?: Collection<unknown>
}

type Props = {
  type: ContentHandlerType
  setItems: Dispatch<SetStateAction<unknown[] | undefined>>
  items: string
  operation: Operation
  collection?: Collection<unknown> | undefined
}

export function CollectionItemPicker({
  type,
  setItems,
  items,
  operation,
  collection,
}: Props) {
  const itemComponent: {
    [K in ContentHandlerType]: React.ComponentType<ComponentProps>
  } = {
    term: CollectionItemTermPicker as React.ComponentType<ComponentProps>,
    // taxon: CollectionItemTaxonPicker as React.ComponentType<ComponentProps>,
    taxon: CollectionInatTaxonPicker as React.ComponentType<ComponentProps>,
    topic: CollectionItemTopicPicker as React.ComponentType<ComponentProps>,
    trait: CollectionItemTraitPicker as React.ComponentType<ComponentProps>,
  }

  const Component = itemComponent[type]

  const showComponent =
    operation === 'create' || (operation === 'update-items' && type !== 'topic')

  return (
    showComponent && (
      <Component
        setItems={setItems}
        items={items}
        operation={operation}
        collection={collection}
      />
    )
  )
}
