import { CldUploadWidget } from 'next-cloudinary'

// Generated by Copilot
import {
  CloudinaryUploadWidgetResults,
  CloudinaryUploadWidgetInfo,
} from 'next-cloudinary'

export const ImageUpload = () => {
  const handleUploadSuccess = (result: CloudinaryUploadWidgetResults) => {
    if (!result.info || typeof result.info === 'string') return
    const info: CloudinaryUploadWidgetInfo = result.info
    console.log('Upload successful:', result)
    console.log('Public ID:', info.public_id)
    // You can access other useful properties like:
    // result.info.secure_url - the full Cloudinary URL
    // result.info.width, result.info.height - image dimensions
    // result.info.format - file format
    // result.info.resource_type - usually 'image'
  }

  const handleUploadError = (error: unknown) => {
    console.error('Upload failed:', error)
  }
  return (
    <CldUploadWidget
      uploadPreset="LTP Collection Context Images"
      options={{
        maxFileSize: 1000000, // 1MB in bytes
      }}
      onSuccess={handleUploadSuccess}
      onError={handleUploadError}
    >
      {({ open }) => {
        return <button onClick={() => open()}>Upload an Image</button>
      }}
    </CldUploadWidget>
  )
}
